# Generated by Django 4.1.2 on 2022-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0002_team_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='matches_won',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
