# Generated by Django 4.1.2 on 2022-10-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_alter_team_matches_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='matches_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
