# Generated by Django 4.1.2 on 2022-10-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0004_alter_team_matches_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='your_time',
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tip.team'),
        ),
    ]
