# Generated by Django 4.1.2 on 2022-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0006_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
