# Generated by Django 4.1.2 on 2022-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0007_match_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='local_time',
        ),
    ]
